"""M29: baseline performance observability — timing recorded, no strict thresholds."""

from __future__ import annotations

import json
import platform
import sys
from pathlib import Path

from modules.runtime.runner import ProcessingRequest, ProcessingRunner

_REPO_ROOT = Path(__file__).resolve().parents[2]
_SNAPSHOT_PATH = _REPO_ROOT / "performance_snapshot.txt"


def test_runner_records_execute_and_total_time(monkeypatch):
    """Minimal txt2img-style path: runner reports execute_time and runtime_total_time."""
    from modules.processing import Processed, StableDiffusionProcessingTxt2Img

    def fake_inner(proc):
        return Processed(proc, [], seed=-1, info="", comments="")

    import modules.processing as proc_mod

    monkeypatch.setattr(proc_mod, "process_images_inner", fake_inner)

    import modules.sd_models as sd_models_mod

    monkeypatch.setattr(sd_models_mod, "reload_model_weights", lambda: None)

    p = StableDiffusionProcessingTxt2Img(
        sd_model=None,
        prompt="m29 perf",
        override_settings={},
        steps=1,
        width=64,
        height=64,
        extra_generation_params={},
    )
    p.scripts = None
    p.comments = []

    req = ProcessingRequest(p)
    runner = ProcessingRunner()
    runner.run(req)

    assert "execute_time" in req.runtime_metrics
    assert "runtime_total_time" in req.runtime_metrics
    assert req.runtime_metrics["execute_time"] >= 0.0
    assert req.runtime_metrics["runtime_total_time"] >= req.runtime_metrics["execute_time"]
    assert hasattr(p, "runtime_metrics")
    assert p.runtime_metrics is req.runtime_metrics

    payload = {
        "milestone": "M29",
        "runner": {
            "execute_time": req.runtime_metrics["execute_time"],
            "runtime_total_time": req.runtime_metrics["runtime_total_time"],
        },
        "python": sys.version.split()[0],
        "platform": platform.platform(),
    }
    lines = [
        "# performance_snapshot.txt — M29 baseline (generated by test/quality/test_performance_baseline.py)",
        "# Not a performance gate; values vary by CPU/GPU and load.",
        json.dumps(payload, indent=2),
    ]
    _SNAPSHOT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
